### PR TITLE
HOP-3 Endpoints

### PR DESCRIPTION
**Pull request by NerdyNinja2417**
I continued with the creation of the Endpoints as assigned on the Jira board. I Created a basic layout of how I might get the endpoints done. However I am tired so I am heading to sleep. If anyone has any tips or suggestions on how they would do it let me know on slack. For now this is my plan.

### CODE REVIEW

**Comment by Nicklozoya** [comment]
Remember in the PR description to mention the jira board story this is associated with.

**Review by estradagabe1996 — APPROVED** [review]
Outline looks good! Me and Zakai are going to help out on the endpoints. I'll take the GET endpoint and Zakai will take the DELETE.

**Comment by MrMeghoo** [comment]
Correct, please ensure that the pull request info is solely related to that of the Jira board content.

**Review by MrMeghoo — APPROVED** [review]
Looks good. Edit the PR comments to match that of the Jira Board content.

**Pull request merged**
