### PR TITLE
HOP-4: Create Login Page 

### PR DESCRIPTION
**Pull request by MrMeghoo**
This login page allows users to enter an existing username and password. It includes button() click functionality.

I will include pushes in "stages" and once the PR for the login page has been completed an title of final stage will be included in the PR title.

### CODE REVIEW

**Review by NerdyNinja2417 — DISMISSED** [review]
Looks good to me. Nice work Zakai.

**Comment by NerdyNinja2417** [comment]
> Looks good to me. Nice work Zakai.

**Comment by MrMeghoo** [comment]
In need of an approval for merging purposes to the main

**Review by Nicklozoya — APPROVED** [review]
looks great

**Pull request merged**
